---
sidebar: sidebar 
permalink: trident-protect/trident-protect-customize-installation.html 
keywords: customize, trident Protect, resource limits, security context constraints, SCC, NetApp AutoSupport, proxy connection, helm, helm chart, helm upgrade 
summary: 特定のニーズに合わせてTrident Protect のデフォルト設定をカスタマイズします。 
---
= Trident Protectのインストールをカスタマイズする
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
環境の特定の要件を満たすように、 Trident Protect のデフォルト構成をカスタマイズできます。



== Trident Protectコンテナのリソース制限を指定する

Trident Protect をインストールした後、構成ファイルを使用してTrident Protect コンテナーのリソース制限を指定できます。リソース制限を設定すると、 Trident Protect 操作によって消費されるクラスターのリソースの量を制御できます。

.手順
. という名前のファイルを作成します `resourceLimits.yaml`。
. 環境のニーズに応じて、 Trident Protect コンテナのリソース制限オプションをファイルに入力します。
+
次の構成ファイルの例は、使用可能な設定を示しています。このファイルには、各リソース制限のデフォルト値が含まれています。

+
[source, yaml]
----
---
jobResources:
  defaults:
    limits:
      cpu: 8000m
      memory: 10000Mi
      ephemeralStorage: ""
    requests:
      cpu: 100m
      memory: 100Mi
      ephemeralStorage: ""
  resticVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  resticVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
----
. ファイルから値を適用し `resourceLimits.yaml`ます。
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f resourceLimits.yaml --reuse-values
----




== セキュリティコンテキスト制約のカスタマイズ

Trident Protect をインストールした後、構成ファイルを使用して、 Trident Protect コンテナーの OpenShift セキュリティ コンテキスト制約 (SCC) を変更できます。これらの制約は、Red Hat OpenShift クラスター内のポッドのセキュリティ制限を定義します。

.手順
. という名前のファイルを作成します `sccconfig.yaml`。
. SCCオプションをファイルに追加し、環境のニーズに応じてパラメータを変更します。
+
次に、SCCオプションのパラメータのデフォルト値の例を示します。

+
[source, yaml]
----
scc:
  create: true
  name: trident-protect-job
  priority: 1
----
+
次の表では、SCCオプションのパラメータについて説明します。

+
|===
| パラメータ | 製品説明 | デフォルト 


| 作成 | SCCリソースを作成できるかどうかを決定します。SCCリソースは、がに設定され `true`、HelmのインストールプロセスでOpenShift環境が指定されている場合にのみ作成され `scc.create`ます。OpenShiftで動作していない場合、またはがに設定されている `false`場合 `scc.create`、SCCリソースは作成されません。 | 正しい 


| 名前 | SCCの名前を指定します。 | Trident - protect-job 


| 優先度 | SCCのプライオリティを定義します。優先度の高いSCCSは、低い値のSCCSよりも先に評価されます。 | 1 
|===
. ファイルから値を適用し `sccconfig.yaml`ます。
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect -f sccconfig.yaml --reuse-values
----
+
これにより、デフォルト値がファイルで指定された値に置き換えられ `sccconfig.yaml`ます。





== Trident Protect のNetApp AutoSupport接続を構成する

接続用のプロキシを設定することで、 Trident Protect がNetAppサポートに接続してサポート バンドルをアップロードする方法を変更できます。ニーズに応じて、安全な接続または安全でない接続のいずれかを使用するようにプロキシを設定できます。

[role="tabbed-block"]
====
.セキュアプロキシ接続の設定
--
.手順
. Trident Protect サポート バンドルのアップロード用に安全なプロキシ接続を構成します。
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect --set autoSupport.proxy=http://my.proxy.url --reuse-values
----


--
.セキュアでないプロキシ接続を設定する
--
.手順
. TLS 検証をスキップする、 Trident Protect サポート バンドルのアップロード用の安全でないプロキシ接続を構成します。
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect --set autoSupport.proxy=http://my.proxy.url --set autoSupport.insecure=true --reuse-values
----


--
====


== Trident Protectポッドを特定のノードに制限する

Kubernetes nodeSelector ノード選択制約を使用すると、ノード ラベルに基づいて、どのノードがTrident Protect ポッドを実行できるかを制御できます。デフォルトでは、 Trident Protect は Linux を実行しているノードに制限されています。ニーズに応じてこれらの制約をさらにカスタマイズできます。

.手順
. という名前のファイルを作成します `nodeSelectorConfig.yaml`。
. nodeSelectorオプションをファイルに追加し、ファイルを変更してノードラベルを追加または変更して、環境のニーズに応じて制限します。たとえば、次のファイルにはデフォルトのOS制限が含まれていますが、特定の地域とアプリ名も対象としています。
+
[source, yaml]
----
nodeSelector:
  kubernetes.io/os: linux
  region: us-west
  app.kubernetes.io/name: mysql
----
. ファイルから値を適用し `nodeSelectorConfig.yaml`ます。
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f nodeSelectorConfig.yaml --reuse-values
----
+
これにより、デフォルトの制限がファイルで指定した制限に置き換えられます `nodeSelectorConfig.yaml`。





== 毎日のTrident Protect AutoSupportバンドルのアップロードを無効にする

オプションで、毎日スケジュールされているTrident Protect AutoSupportサポート バンドルのアップロードを無効にすることができます。


NOTE: デフォルトでは、 Trident Protect は、クラスターと管理対象アプリケーションに関するログ、メトリック、トポロジ情報など、開く可能性のあるNetAppサポート ケースに役立つサポート情報を収集します。 Trident Protect は、これらのサポート バンドルを毎日スケジュールに従ってNetAppに送信します。手動でlink:trident-protect-generate-support-bundle.html["サポートバンドルの生成"]いつでも。

.手順
. という名前のファイルを作成します `autosupportconfig.yaml`。
. AutoSupportオプションをファイルに追加し、環境のニーズに応じてパラメータを変更します。
+
次の例は、AutoSupportオプションのパラメータのデフォルト値を示しています。

+
[source, yaml]
----
autoSupport:
  enabled: true
----
+
 `autoSupport.enabled`をに設定する `false`と、AutoSupportサポートバンドルの日次アップロードが無効になります。

. ファイルから値を適用し `autosupportconfig.yaml`ます。
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect -f autosupportconfig.yaml --reuse-values
----

